app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class Quote:

    def __init__(self,author,quote):
        self.author = author
        self.quote = quote



class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    bio = db.Column(db.String(255))
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    pass_secure = db.Column(db.String(255))


    posts = db.relationship('Post', backref='author', lazy=True)
    comments = db.relationship('Comment', backref = 'user', lazy ='dynamic')


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'



class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy = "dynamic")

    def __repr__(self):
        return f'User {self.name}'



class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)



    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"



class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment =  db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))
    posted = db.Column(db.DateTime,default=datetime.utcnow)

    

    

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    
    @classmethod
    def get_comments(cls):
        comments= Comment.query.filter_by(post_id=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required


class BlogForm(FlaskForm):

    
    title = StringField('Blog title',validators=[Required()])
    content = TextAreaField('Blog', validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment = TextAreaField("Leave a comment", validators = [Required()])
    submit = SubmitField("Post")


class SubForm(FlaskForm):
    submit = SubmitField("Get notifications for every new blog")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import Config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_wtf.csrf import CSRFProtect
import os


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'



bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
csrf = CSRFProtect()


app = Flask(__name__)

def create_app(config_name):

    app = Flask(__name__)

    app.config.from_object(Config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    csrf.init_app(app)


    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from .forms import BlogForm,CommentForm,SubForm
from flask_login import login_required, current_user
from .. import db
from ..models import User,Post,Comment
from ..gmail import mail_message
from ..requests import get_quotes



@main.route('/')
def index():

    

    posts = Post.query.all()
    quote = get_quotes()

    
    title = 'K Blog'
    return render_template('index.html',title = title,posts =posts,quote=quote)



@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    title = f'{uname} profile'


    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user, title = title)




@main.route('/blog', methods = ['GET','POST'])
@login_required
def new_post():
    blog_form = BlogForm()
    sub_form = SubForm()

    if blog_form.validate_on_submit():
        post = Post(title=blog_form.title.data, content=blog_form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))

        if sub_form.validate_on_submit():
            mail_message("NEW BLOG","gmail/sucription",user.email,user,user=user)
            flash('You have subscribed to notifications','success')

    title = 'New Blog'
    return render_template('blog.html' ,title = title, blog_form = blog_form,sub_form=sub_form)



@main.route('/blog/<int:post_id>/comment', methods = ['GET','POST'])
@login_required
def comment(post_id):
    comment_form = CommentForm()
    my_blog = Post.query.get(post_id)

    if my_blog is None:
        abort(404)
    

    if comment_form.validate_on_submit():
        comment = comment_form.comment.data
        new_comment = Comment(comment = comment, post_id = post_id, user = current_user)
        new_comment.save_comment()
        return redirect(url_for('main.comment', post_id=post_id))

    all_comments = Comment.query.filter_by(post_id=post_id).all()

    title = 'comment'
    return render_template('comment.html' ,title = title, comment_form = comment_form, comment=all_comments,)


@main.route('/blog/<int:post_id>/update', methods =['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get(post_id)
    if post.author != current_user:
        abort(403)
    blog_form = BlogForm()
    if blog_form.validate_on_submit():
        post.title = blog_form.title.data
        post.content = blog_form.content.data
        db.session.commit()
        flash('Your blog has been updated!', 'success')
        return redirect(url_for('main.index', post_id=post.id))
    elif request.method == 'GET':
        blog_form.title.data = post.title
        blog_form.content.data = post.content
    return render_template('blog.html',title = 'Update post', blog_form=blog_form)


@main.route('/blog/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get(post_id)
    if post.author == current_user:
        db.session.delete(post)
        db.session.commit()
        flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))




    

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}


{% block styles%}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='index.css')}}">
{% endblock %}

{% block content %}
    <div class="container box" id="formz">
        <div class="col-md-4"></div>
            {{blog_form.csrf_token}}
            {{ wtf.quick_form(blog_form) }}
        </div>
    </div>
{% endblock %}

app/templates/comment.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">
        <div class="col-md-4">
            {{ wtf.quick_form(comment_form) }}
        </div>
    </div>
    <div class="container">
        {{macro.displayComments(comment)}}
    </div>

    
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='index.css')}}">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500&family=Righteous&display=swap" rel="stylesheet">
{% endblock %}
  
  

{% block content %}
  <div class="text-center">
      <p style="font-size: xx-large;"><strong>{{quote.quote}}</strong></p>
      <p>{{quote.author}}</p>
  </div> 
  <br>
  <br>    
  {% for post in posts %}        
    
    <div class="card">
      <div class="card-header" style="font-size: x-large; font-family: 'Righteous', cursive;
      font-family: 'Barlow Condensed', sans-serif; text-decoration: underline;">
        {{post.title}}
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p>{{ post.content }}</p>
          <br><br>
          <button class="btn btn-default"><a href="{{url_for('main.comment',post_id=post.id)}}">Comment</a></button>
          {% if post.author == current_user %}
            <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('main.update_post', post_id=post.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
          {% endif %}

          <footer class="blockquote-footer">posted on {{post.date_posted.strftime('%d/%m/%Y')}}</footer>
        </blockquote>
      </div>
    </div>
  

    <!--Modal section-->


    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('main.delete_post', post_id=post.id) }}" method="POST">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              <input class="btn btn-danger" type="submit" value="Delete">
              
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}





{% endblock %}

app/templates/macros.html
{% macro displayComments(all_comments)%}
    {% if all_comments%}

        {% for comment in all_comments %}
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">

            <div class="media-body">
                <h4>{{comment.user.username}}</h4>
                <p>{{comment.comment}}</p>
            </div>

        </div>
        {% endfor %}
    {% endif %}

{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse navbar-light" role="navigation" style="background-color: #e3f2fd;">
  <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">KBLOG</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"> HOME </a>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/blog">+Add Blog</a></li>
            {% if current_user.is_authenticated %}
              <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
              <li><a href="{{url_for('auth.logout')}}">Log out</a></li>
            {% else %}  
              <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
      
            {%endif%}
          </ul>
      </div>

  </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>

  <!-- Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}


    {% if user == current_user %}
        <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

            <input type="file"  name="photo" class="form-control" required>
            <input type="submit">
  
        </form>
    {% endif%}
    <p>Number of pitches: {{user.pitches.count()}}</p>
  </div>

</div>
</div>
{% endblock %}